export default {
  FETCH_START: 'movies/FETCH_START',
  FETCH_SUCCESS: 'movies/FETCH_SUCCESS',
  FETCH_FAILURE: 'movies/FETCH_FAILURE',
  SEARCH_START: 'movies/SEARCH_START',
  SEARCH_SUCCESS: 'movies/SEARCH_SUCCESS',
  SEARCH_FAILURE: 'movies/SEARCH_FAILURE',
};
